// tailwind.config.js
const plugin = require('tailwindcss/plugin');

module.exports = {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				primary: 'var(--color-primary)',
				'primary-light': 'var(--color-primary-light)',
				'primary-dark': 'var(--color-primary-dark)',
				secondary: 'var(--color-secondary)',
				accent: 'var(--color-accent)',
				background: 'var(--color-background)',
				foreground: 'var(--color-foreground)',
				muted: 'var(--color-muted)',
				'muted-light': 'var(--color-muted-light)',
				border: 'var(--color-border)',
				'border-light': 'var(--color-border-light)',
			},
			fontFamily: {
				base: 'var(--font-family-base)',
				heading: 'var(--font-family-heading)',
				mono: 'var(--font-family-mono)',
			},
			fontSize: {
				xs: 'var(--font-size-xs)',
				sm: 'var(--font-size-sm)',
				base: 'var(--font-size-base)',
				lg: 'var(--font-size-lg)',
				xl: 'var(--font-size-xl)',
				'2xl': 'var(--font-size-2xl)',
				'3xl': 'var(--font-size-3xl)',
				'4xl': 'var(--font-size-4xl)',
				'5xl': 'var(--font-size-5xl)',
				'6xl': 'var(--font-size-6xl)',
			},
			fontWeight: {
				light: 'var(--font-weight-light)',
				normal: 'var(--font-weight-normal)',
				medium: 'var(--font-weight-medium)',
				semibold: 'var(--font-weight-semibold)',
				bold: 'var(--font-weight-bold)',
				extrabold: 'var(--font-weight-extrabold)',
				black: 'var(--font-weight-black)',
			},
			lineHeight: {
				tight: 'var(--line-height-tight)',
				snug: 'var(--line-height-snug)',
				normal: 'var(--line-height-normal)',
				relaxed: 'var(--line-height-relaxed)',
				loose: 'var(--line-height-loose)',
			},
			spacing: {
				1: 'var(--space-1)',
				2: 'var(--space-2)',
				3: 'var(--space-3)',
				4: 'var(--space-4)',
				5: 'var(--space-5)',
				6: 'var(--space-6)',
				8: 'var(--space-8)',
				10: 'var(--space-10)',
				12: 'var(--space-12)',
				16: 'var(--space-16)',
				20: 'var(--space-20)',
				24: 'var(--space-24)',
				32: 'var(--space-32)',
			},
			borderRadius: {
				sm: 'var(--radius-sm)',
				md: 'var(--radius-md)',
				lg: 'var(--radius-lg)',
				xl: 'var(--radius-xl)',
				'2xl': 'var(--radius-2xl)',
				'3xl': 'var(--radius-3xl)',
				full: 'var(--radius-full)',
			},
			boxShadow: {
				sm: 'var(--shadow-sm)',
				md: 'var(--shadow-md)',
				lg: 'var(--shadow-lg)',
				xl: 'var(--shadow-xl)',
				'2xl': 'var(--shadow-2xl)',
			},
			transitionDuration: {
				fast: 'var(--transition-fast)',
				normal: 'var(--transition-normal)',
				slow: 'var(--transition-slow)',
			},
			zIndex: {
				dropdown: 'var(--z-dropdown)',
				sticky: 'var(--z-sticky)',
				fixed: 'var(--z-fixed)',
				'modal-backdrop': 'var(--z-modal-backdrop)',
				modal: 'var(--z-modal)',
				popover: 'var(--z-popover)',
				tooltip: 'var(--z-tooltip)',
			},
		},
	},
	plugins: [
		plugin(function ({ addBase, addComponents, addUtilities }) {
			// Add base styles
			addBase({
				':root': {
					'--color-primary': '#3b82f6',
					'--color-primary-light': '#60a5fa',
					'--color-primary-dark': '#1d4ed8',
					'--color-secondary': '#8b5cf6',
					'--color-accent': '#f59e0b',
					'--color-background': '#ffffff',
					'--color-foreground': '#0f172a',
					'--color-muted': '#64748b',
					'--color-muted-light': '#94a3b8',
					'--color-border': '#e2e8f0',
					'--color-border-light': '#f1f5f9',
					'--font-family-base': "'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
					'--font-family-heading': "'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
					'--font-family-mono': "'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace",
					'--font-size-xs': '0.75rem',
					'--font-size-sm': '0.875rem',
					'--font-size-base': '1rem',
					'--font-size-lg': '1.125rem',
					'--font-size-xl': '1.25rem',
					'--font-size-2xl': '1.5rem',
					'--font-size-3xl': '1.875rem',
					'--font-size-4xl': '2.25rem',
					'--font-size-5xl': '3rem',
					'--font-size-6xl': '3.75rem',
					'--font-weight-light': '300',
					'--font-weight-normal': '400',
					'--font-weight-medium': '500',
					'--font-weight-semibold': '600',
					'--font-weight-bold': '700',
					'--font-weight-extrabold': '800',
					'--font-weight-black': '900',
					'--line-height-tight': '1.25',
					'--line-height-snug': '1.375',
					'--line-height-normal': '1.5',
					'--line-height-relaxed': '1.625',
					'--line-height-loose': '2',
					'--space-1': '0.25rem',
					'--space-2': '0.5rem',
					'--space-3': '0.75rem',
					'--space-4': '1rem',
					'--space-5': '1.25rem',
					'--space-6': '1.5rem',
					'--space-8': '2rem',
					'--space-10': '2.5rem',
					'--space-12': '3rem',
					'--space-16': '4rem',
					'--space-20': '5rem',
					'--space-24': '6rem',
					'--space-32': '8rem',
					'--radius-sm': '0.25rem',
					'--radius-md': '0.375rem',
					'--radius-lg': '0.5rem',
					'--radius-xl': '0.75rem',
					'--radius-2xl': '1rem',
					'--radius-3xl': '1.5rem',
					'--radius-full': '9999px',
					'--shadow-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
					'--shadow-md': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
					'--shadow-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
					'--shadow-xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
					'--shadow-2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
					'--transition-fast': '150ms cubic-bezier(0.4, 0, 0.2, 1)',
					'--transition-normal': '300ms cubic-bezier(0.4, 0, 0.2, 1)',
					'--transition-slow': '500ms cubic-bezier(0.4, 0, 0.2, 1)',
					'--z-dropdown': '1000',
					'--z-sticky': '1020',
					'--z-fixed': '1030',
					'--z-modal-backdrop': '1040',
					'--z-modal': '1050',
					'--z-popover': '1060',
					'--z-tooltip': '1070',
				},
			});

			// Dark theme variables
			addBase({
				'.dark': {
					'--color-background': '#0f172a',
					'--color-foreground': '#f8fafc',
					'--color-primary': '#60a5fa',
					'--color-primary-light': '#93c5fd',
					'--color-primary-dark': '#3b82f6',
					'--color-secondary': '#a78bfa',
					'--color-accent': '#fbbf24',
					'--color-muted': '#94a3b8',
					'--color-muted-light': '#cbd5e1',
					'--color-border': '#334155',
					'--color-border-light': '#1e293b',
				},
			});

			// Add utility components
			addComponents({
				'.btn': {
					display: 'inline-flex',
					alignItems: 'center',
					justifyContent: 'center',
					gap: 'var(--space-2)',
					padding: 'var(--space-3) var(--space-6)',
					fontFamily: 'var(--font-family-base)',
					fontSize: 'var(--font-size-sm)',
					fontWeight: 'var(--font-weight-medium)',
					lineHeight: 'var(--line-height-normal)',
					textDecoration: 'none',
					border: 'none',
					borderRadius: 'var(--radius-lg)',
					cursor: 'pointer',
					transition: 'all var(--transition-normal)',
					userSelect: 'none',
					whiteSpace: 'nowrap',
				},
				'.btn-primary': {
					background: 'linear-gradient(135deg, var(--color-primary) 0%, var(--color-primary-dark) 100%)',
					color: 'white',
					boxShadow: 'var(--shadow-md)',
				},
				'.btn-primary:hover': {
					transform: 'translateY(-2px)',
					boxShadow: 'var(--shadow-lg)',
				},
				'.card': {
					background: 'var(--color-background)',
					border: '1px solid var(--color-border)',
					borderRadius: 'var(--radius-xl)',
					padding: 'var(--space-6)',
					boxShadow: 'var(--shadow-sm)',
					transition: 'all var(--transition-normal)',
				},
				'.card:hover': {
					transform: 'translateY(-4px)',
					boxShadow: 'var(--shadow-lg)',
					borderColor: 'var(--color-border-light)',
				},
			});

			// Add utility classes
			addUtilities({
				'.text-gradient': {
					background: 'linear-gradient(135deg, var(--color-primary) 0%, var(--color-secondary) 100%)',
					'-webkit-background-clip': 'text',
					'-webkit-text-fill-color': 'transparent',
					'background-clip': 'text',
				},
				'.text-balance': {
					'text-wrap': 'balance',
				},
				'.text-pretty': {
					'text-wrap': 'pretty',
				},
			});
		}),
	],
};
